image: node:6.4

stages:
  - build
  - deploy

build site:
  stage: build
  script:
    - cd PettyCash && npm install --progress=false
    - npm run build
  artifacts:
    expire_in: 1h
    paths:
      - dist

deploy:
  image: alpine
  stage: deploy
  script:
    - apk add --no-cache rsync openssh
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" >> ~/.ssh/id_dsa
    - chmod 600 ~/.ssh/id_dsa
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - rsync -rav --delete dist/ $USER@$SERVER_IP:/var/www/pettycash-app.nfortics.com
  only:
    - master
